GlucoseTrackerWeb/GlucoseTrackerWeb/Controllers/DataController.cs
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//	Solution/Project:  GlucoseTrackerWeb/GlucoseTrackerWeb
//	File Name:         DataController.cs
//	Description:       Controller for all Data.
//	Author:            Matthew McPeak, McPeakML@etsu.edu
//  Copyright:         Matthew McPeak, 2019
//  Team:              Sour Patch Kids
//
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Collections.Generic;
using System.Linq;
using GlucoseAPI.Models.Entities;
using GlucoseAPI.Services;
using GlucoseTrackerWeb.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace GlucoseTrackerWeb.Controllers
{
    /// <summary>
    /// Controller for all Data.
    /// </summary>
    public class DataController : Controller
    {

        #region Dependency Injection
        IRepository<Patient> _patientRepo;
        IRepository<MealItem> _mealRepo;

        public DataController(IRepository<Patient> patientRepo, IRepository<MealItem> mealRepo)
        {
            _patientRepo = patientRepo;
            _mealRepo = mealRepo;

        }

        #endregion

        #region Patient Data
        /// <summary>
        /// Returns the Patient Data. For the Appropriate Patient 
        /// </summary>
        /// <param name="id">A Patient Id</param>
        /// <returns>The Patient Data View</returns>
        [HttpPost]
        public IActionResult Index([FromForm(Name = "id")] int id)
        {
            //The Doctor is logged in
            if (!(HttpContext.Session.GetString("TokenAuth") is null))
            {
                //Read the Patient.
                Patient patient = _patientRepo.Read(p => p.UserId == id, p => p.PatientBloodSugars, p => p.PatientCarbs, p => p.PatientExercises);

                //List of All Meals
                List<MealItem> meals = _mealRepo.ReadAll().ToList();

                //Order the Lists.
                patient.PatientBloodSugars = patient.PatientBloodSugars.OrderBy(bs => bs.TimeOfDay).ToList();
                patient.PatientCarbs = patient.PatientCarbs.OrderBy(pc => pc.TimeOfDay).ToList();
                patient.PatientExercises = patient.PatientExercises.OrderBy(pe => pe.TimeOfDay).ToList();

                //Key Value Pairs for JavaScript Chart.js
                Dictionary<DateTime, float> bloodSugarsBefore = new Dictionary<DateTime, float>();
                Dictionary<DateTime, float> bloodSugarsAfter = new Dictionary<DateTime, float>();
                Dictionary<DateTime, float> exercises = new Dictionary<DateTime, float>();
                Dictionary<DateTime, float> carbs = new Dictionary<DateTime, float>();

                //For each bloodSugar.
                foreach (var bloodSugar in patient.PatientBloodSugars)
                {
                    //Assign the Appropriate Meal.
                    bloodSugar.Meal = meals.FirstOrDefault(m => m.MealId == bloodSugar.MealId);

                    //Add the BloodSugars Appropriately to the Dictionary 
                    if (bloodSugar.ReadingType == ReadingType.Before)
                    {
                        bloodSugarsBefore.Add(bloodSugar.TimeOfDay, bloodSugar.Level);
                    }
                    else
                    {
                        bloodSugarsAfter.Add(bloodSugar.TimeOfDay, bloodSugar.Level);
                    }
                }

                //For each carb.
                foreach (var carb in patient.PatientCarbs)
                {
                    //Assign the Appropriate Meal
                    carb.Meal = meals.FirstOrDefault(m => m.MealId == carb.MealId);

                    //Add the Carb Appropriately to the Dictionary
                    carbs.Add(carb.TimeOfDay, carb.FoodCarbs);
                }

                //For each exercise.
                foreach (var exercise in patient.PatientExercises)
                {
                    //Add the Exercise Appropriately to the Dictionary
                    exercises.Add(exercise.TimeOfDay, exercise.HoursExercised);
                }

                //Create a new PatientData View Model
                PatientDataVM patientDataVM = new PatientDataVM()
                {
                    FullName = $"{patient.LastName}, {patient.FirstName}",
                    PatientExercises = patient.PatientExercises,
                    PatientBloodSugars = patient.PatientBloodSugars,
                    PatientCarbohydrates = patient.PatientCarbs
                };

                //Assign ViewData for Chart.js
                ViewData["BloodSugarsBefore"] = JsonConvert.SerializeObject(bloodSugarsBefore);
                ViewData["BloodSugarsAfter"] = JsonConvert.SerializeObject(bloodSugarsAfter);
                ViewData["Exercises"] = JsonConvert.SerializeObject(exercises);
                ViewData["Carbs"] = JsonConvert.SerializeObject(carbs);

                //return the View with the Patient Data View Model
                return View(patientDataVM);
            }
            else
            {
                //Otherwise.. Redirect to Login
                return RedirectToAction("Index", "Home");
            }
        }
        #endregion
    }
}

GlucoseTrackerWeb/GlucoseTrackerWeb/Controllers/HomeController.cs
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//
//	Solution/Project:  GlucoseTrackerWeb/GlucoseTrackerWeb
//	File Name:         HomeController.cs
//	Description:       Controller for all Doctor Related Tasks
//	Author:            Matthew McPeak, McPeakML@etsu.edu
//  Copyright:         Matthew McPeak, 2019
//  Team:              Sour Patch Kids
//
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
using System;
using System.Diagnostics;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using GlucoseAPI.Models.Entities;
using GlucoseAPI.Services;
using static BCrypt.Net.BCrypt;
using GlucoseAPI.Models;

namespace GlucoseTrackerWeb.Controllers
{
    /// <summary>
    /// Controller for all Doctor Related Tasks
    /// </summary>
    public class HomeController : Controller
    {
        #region Dependency Injection
        private readonly IRepository<Doctor> _doctorRepo;
        private readonly IRepository<Patient> _patientRepo;
        private readonly IRepository<Auth> _authRepo;
        private readonly IRepository<TokenAuth> _tokenAuthRepo;

        public HomeController(IRepository<Doctor> doctorRepo, IRepository<Patient> patientRepo, IRepository<Auth> authRepo, IRepository<TokenAuth> tokenAuthRepo)
        {
            _doctorRepo = doctorRepo;
            _patientRepo = patientRepo;
            _authRepo = authRepo;
            _tokenAuthRepo = tokenAuthRepo;
        }
        #endregion

        #region Auth/DeAuth
        /// <summary>
        /// Authentication for Doctors
        /// </summary>
        /// <param name="creds">A Doctor's Credentials</param>
        /// <returns>A page based upon auth status</returns>
        [HttpPost]
        public IActionResult Login(Credentials creds)
        {
            //Try to Authenticate
            try
            {
                //Find Authorization based up on Credentials
                Auth authorization = _authRepo.Read(a => a.Email == creds.Email);
                TokenAuth tokenAuthorization = _tokenAuthRepo.Read(ta => ta.AuthId == authorization.AuthId);

                //Read the Doctor
                Doctor doctor = _doctorRepo.Read(d => d.Email == creds.Email);

                //If the doctor exists and is authed.
                if (!(doctor is null) && Verify(creds.Password, authorization.Password))
                {
                    //Set a Session
                    HttpContext.Session.SetString("TokenAuth", tokenAuthorization.Token);

                    //Redirect to the Landing Page
                    return RedirectToAction("Dashboard", "Home");
                    
                }

                //Otherwise.. Assign A Temp Var called BadLogin
                TempData["BadLogin"] = true;

                //return the Login Page.
                return View("Index");
            }
            catch (Exception)
            {
                //Otherwise.. Assign A Temp Var called BadLogin
                TempData["BadLogin"] = true;

                //return the Login Page.
                return View("Index");
            }
        }

        /// <summary>
        /// DeAuth for Doctors
        /// </summary>
        /// <returns>The Login Page</returns>
        public IActionResult Logout()
        {
            //Empty Session and Redirect to Login.
            HttpContext.Session.Clear();
            Response.Cookies.Delete("TokenAuth");
            return RedirectToAction("Index");
        }
        #endregion

        #region Login Page
        /// <summary>
        /// Login Page.
        /// </summary>
        /// <returns>A View based upon login status</returns>
        public IActionResult Index()
        {
            //If the Doctor is Logged-In
            if (!(HttpContext.Session.GetString("TokenAuth") is null))
            {
                //Display Landing Page
                return RedirectToAction("Dashboard", "Home");

            }
            else
            {
                //Display
                return View();
            }
        }
        #endregion

        #region Registration 
        /// <summary>
        /// Create View for Doctor.
        /// </summary>
        /// <returns>The Create Doctor Form</returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Creates a new Doctor
        /// </summary>
        /// <param name="doctorCreationBundle">A Doctor Creation Bundle</param>
        /// <returns>The Index Page upon Success</returns>
        [HttpPost]
        public IActionResult Create(DoctorCreationBundle doctorCreationBundle)
        {
            //If the Model is valid.
            if (ModelState.IsValid)
            {
                //Try to create a doctor
                try
                {
                    //Create new Auth Entries.
                    Auth authEntry = new Auth()
                    {
                        Email = doctorCreationBundle.Doctor.Email,
                        Password = HashPassword(doctorCreationBundle.Password)
                    };

                    TokenAuth TokenAuthEntry = new TokenAuth()
                    {
                        Token = HashPassword(authEntry.Password),
                        Auth = authEntry,
                        User = doctorCreationBundle.Doctor
                    };

                    _authRepo.Create(authEntry);
                    _tokenAuthRepo.Create(TokenAuthEntry);

                    //Redirect to Login
                    return RedirectToAction("Index");
                }
                catch (Exception)
                {
                    if(_doctorRepo.ReadAll().ToList().Any(d => d.Email == doctorCreationBundle.Doctor.Email))
                    {
                        TempData["UserExists"] = true;
                    }
                    //Otherwise... Return the Create view.
                    return View(doctorCreationBundle);
                }
            }
            else
            {
                //Otherwise... Return the Create view
                return View(doctorCreationBundle);
            }
        }
        #endregion

        #region Assign Patient
        /// <summary>
        /// Add a Patient View
        /// </summary>
        /// <returns>The Add a Patient View</returns>
        public IActionResult AddPatient()
        {
            //Verify the Doctor is Logged In
            if (!(HttpContext.Session.GetString("TokenAuth") is null))
            {
                //Return the View.
                return View();
            }
            else
            {
                //Otehrwise... Redirect to Login
                return RedirectToAction("Index");
            }
        }

        /// <summary>
        /// Adds a Pattient to a Doctor
        /// </summary>
        /// <param name="token">A Patient's token</param>
        /// <returns>The Dashboard View Upon Success</returns>
        [HttpPost]
        public IActionResult AddPatient([FromForm(Name = "token")] string token)
        {
            //If the Doctor is Logged-In
            if (!(HttpContext.Session.GetString("TokenAuth") is null))
            {
                //Try to add a Patient
                try
                {
                    //Query the Patient
                    Patient patient = _tokenAuthRepo.Read(ta => ta.Token.Substring(ta.Token.Length -6, 6) == token , ta => ta.User).User as Patient;

                    //Query the Doctor
                    Doctor doctor = _tokenAuthRepo.Read(ta => ta.Token == HttpContext.Session.GetString("TokenAuth"), ta => ta.User).User as Doctor;

                    //Assign the Doctor to the Patient
                    patient.DoctorId = doctor.UserId;
                    patient.Doctor = doctor;

                    //Update the Patient
                    _patientRepo.Update(patient);

                    //Redirect to Landing Page
                    return RedirectToAction("Dashboard");
                }
                catch (Exception)
                {
                    //Otherwise.. Invalid Token and Display and Error
                    TempData["BadUser"] = true;
                    return View();
                }
            }
            else
            {
                //Otehrwise... Return to Login 
                return RedirectToAction("Index");
            }

        }
        #endregion

        #region Remove Patient

        /// <summary>
        /// Removes a pateint from a doctor
        /// </summary>
        /// <param name="id">A Patient Id</param>
        /// <returns>The Dashboard View</returns>
        [HttpPost]
        public IActionResult RemovePatient([FromForm(Name = "id")] int id)
        {
            //If the Doctor is Logged-In
            if (!(HttpContext.Session.GetString("TokenAuth") is null))
            {
                //Try to Remove the Patient
                try
                {
                    //Find the Patient
                    Patient patient = _patientRepo.Read(p => p.UserId == id);

                    //Remove the Doctor from the Patient
                    patient.DoctorId = null;
                    patient.Doctor = null;

                    //Update the Patient
                    _patientRepo.Update(patient);

                    //Return the Landing Page
                    return RedirectToAction("Dashboard");
                }
                catch (Exception)
                {
                    //Otherwise... Set an Error and return the landing page. 
                    TempData["BadUser"] = true;
                    return RedirectToAction("Dashboard");
                }
            }
            else
            {
                //Otherwise.. Redirect to the Login Page. 

GlucoseTrackerWeb/GlucoseTrackerWeb/Views/Home/AddPatient.cshtml
@model GlucoseAPI.Models.Entities.Patient

@{
    //Title.
    ViewData["Title"] = "Track Patient";

    //Assign tokenStatus
    var tokenStatus = TempData["BadUser"];

    //If tokenStatus is set.
    if (!(tokenStatus is null))
    {
        //If the Token was bad. Display an error.
        if ((Boolean)tokenStatus)
        {
            <div class="alert alert-danger alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <h4 class="alert-heading">Error!</h4>
                <p class="mb-0">Invalid Token</p>
            </div>
            }
        }
    }
    <body class="bg-dark">

        <h1>Add A Patient</h1>

        <div class="row">
            <div class="col-md-4">
                <form asp-action="AddPatient">
                    <div class="form-group">
                        <label class="control-label">Token</label>
                        <input name="token" class="form-control" />
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Add" class="btn btn-primary" />
                    </div>
                </form>
            </div>
        </div>

        <div>
            <a asp-action="Index">Back to Dashboard</a>
        </div>
    </body>

GlucoseTrackerWeb/GlucoseTrackerWeb/Views/Home/Create.cshtml
@model GlucoseAPI.Models.Entities.DoctorCreationBundle

@{
    ViewData["Title"] = "Create a New Doctor";

    //Assign the TempData BadLogin var.
    var existStatus = TempData["UserExists"];

    //Verify this is set.
    if (!(existStatus is null))
    {
        //If it was a bad login attemmpt show an error.
        if ((Boolean)existStatus)
        {
            <div class="alert alert-danger alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <h4 class="alert-heading">Error!</h4>
                <p class="mb-0">User Exists</p>
            </div>
        }
    }
}

<h1>@ViewData["Title"]</h1>
<br />
<body class="bg-dark">
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label class="control-label">E-Mail</label>
                    <input type="email" asp-for="Doctor.Email" class="form-control" />
                    <span asp- asp-validation-for="Doctor.Email" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Password</label>
                    <input type="password" asp-for="Password" class="form-control" />
                    <span asp-validation-for="Password" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">First Name</label>
                    <input asp-for="Doctor.FirstName" class="form-control" />
                    <span asp-validation-for="Doctor.FirstName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Middle Name</label>
                    <input asp-for="Doctor.MiddleName" class="form-control" />
                    <span asp-validation-for="Doctor.MiddleName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Last Name</label>
                    <input asp-for="Doctor.LastName" class="form-control" />
                    <span asp-validation-for="Doctor.LastName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label class="control-label">Phone Number</label>
                    <input type="tel" asp-for="Doctor.PhoneNumber" class="form-control" />
                    <span asp-validation-for="Doctor.PhoneNumber" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Back to Login</a>
    </div>
</body>

GlucoseTrackerWeb/GlucoseTrackerWeb/Views/Home/Dashboard.cshtml
@model IEnumerable<GlucoseAPI.Models.Entities.Patient>

@{
    ViewData["Title"] = "Dashboard";
    if (!(TempData["BadUser"] is null))
    {
        if ((Boolean)TempData["BadUser"])
        {
            <div class="alert alert-dismissible alert-danger">
                <h4 class="alert-heading">Error!</h4>
                <p class="mb-0">Invalid User</p>
            </div>
        }
    }
}
            <body class="bg-dark">
                <h1>Patients</h1>
                <p></p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                Full Name
                            </th>
                            <th>
                                Email
                            </th>
                            <th>
                                Phone Number
                            </th>
                            <th>
                                Patient Data
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @($"{item.LastName}, {item.FirstName}")
                                </td>
                                <td>
                                    @item.Email
                                </td>
                                <td>
                                    @($"({item.PhoneNumber.Substring(0, 3)}) {item.PhoneNumber.Substring(3, 3)}-{item.PhoneNumber.Substring(6, 4)}")
                                </td>
                                <td>
                                    <form method="post">
                                        <input type="hidden" name="id" value="@item.UserId" />
                                        <input class="btn btn-warning" asp-controller="Data" asp-action="Index" type="submit" value="See Data">
                                        <input class="btn btn-danger" asp-action="RemovePatient" type="submit" value="Remove Patient">
                                    </form>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
                <a class="btn btn-primary" asp-action="AddPatient">Add Patient</a>
            </body>

GlucoseTrackerWeb/GlucoseTrackerWeb/Views/Home/Index.cshtml
@model GlucoseAPI.Models.Entities.Credentials

@{
    //Title
    ViewData["Title"] = "Login to GlucoseTracker";

    //Assign the TempData BadLogin var.
    var loginStatus = TempData["BadLogin"];

    //Verify this is set.
    if (!(loginStatus is null))
    {
        //If it was a bad login attemmpt show an error.
        if ((Boolean)loginStatus)
        {
            <div class="alert alert-danger alert-dismissible">
                <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                <h4 class="alert-heading">Error!</h4>
                <p class="mb-0">Wrong Email or Password. Please Try Again.</p>
            </div>
        }
    }
}
<body class="bg-dark">
    <div class="text-center">
        <h1 class="display-4">Welcome to Glucose Tracker</h1>
    </div>
    <form asp-action="Login">
        <fieldset>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Email" for="email">Email address</label>
                <input asp-for="Email" type="email" class="form-control" id="email" placeholder="Enter email">
            </div>
            <div class="form-group">
                <label asp-for="Password" for="password">Password</label>
                <input asp-for="Password" type="password" class="form-control" id="password" placeholder="Password">
            </div>
            <button type="submit" class="btn btn-primary">Login</button>
            <a class="btn btn-secondary" asp-controller="Home" asp-action="Create">Register</a>
        </fieldset>
    </form>
</body>